# Generated by Django 5.0.3 on 2024-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="address",
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
